#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker123"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "e0c11c0482f34e2ea8ff0a98d435dcb4" }
]

[assets]
directory = "./public"
